<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('personas')->insert([
            ['per_nit' => '84023899', 'per_nombre' => 'OLY, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '12522732', 'per_nombre' => 'DHL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '35317043', 'per_nombre' => 'BAN, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '104219122', 'per_nombre' => 'ZIR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '43236782', 'per_nombre' => 'OEP, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '79028985', 'per_nombre' => 'ALEM, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '69561362', 'per_nombre' => 'RBSR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '69563845', 'per_nombre' => 'RBSS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '107778602', 'per_nombre' => 'SEFE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '89443209', 'per_nombre' => 'RBHP, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '77849035', 'per_nombre' => 'A Y G, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '79519334', 'per_nombre' => 'GOGAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '88857867', 'per_nombre' => 'BINAR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '89681738', 'per_nombre' => 'JODYS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7269595', 'per_nombre' => 'FERCA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5464064', 'per_nombre' => 'PATSY, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '100004822', 'per_nombre' => 'YAYARB, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '12521337', 'per_nombre' => 'INFILE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '63858517', 'per_nombre' => 'DUNAM , S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '48253944', 'per_nombre' => 'LUCAFE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '84311525', 'per_nombre' => 'PRONTO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '44354312', 'per_nombre' => 'RADILY, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '81817940', 'per_nombre' => 'DISCOL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '103236775', 'per_nombre' => 'LENITA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '67438598', 'per_nombre' => 'CEFALU, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '36585602', 'per_nombre' => 'YI-HOU, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '105124443', 'per_nombre' => 'JUGARSA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '64210529', 'per_nombre' => 'TERANET, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '95590951', 'per_nombre' => 'ASISRED, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5382076', 'per_nombre' => 'INTELAF, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '70275815', 'per_nombre' => 'CANTATA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26025876', 'per_nombre' => 'ALTUNA , S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5559731', 'per_nombre' => 'BELLUNO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '700141K', 'per_nombre' => 'PLATINO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26532476', 'per_nombre' => 'UNISUPER, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '101438478', 'per_nombre' => 'SAGASABI, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '70746273', 'per_nombre' => 'ARANKENE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '67069843', 'per_nombre' => 'OIL\'S MK, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '34589856', 'per_nombre' => 'GRUPO HR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5365651', 'per_nombre' => 'MAYORPIT, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '96227230', 'per_nombre' => 'PETROZAC, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '8347093', 'per_nombre' => 'ULTRACOM, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '8290962', 'per_nombre' => 'SERVICAT, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '667277', 'per_nombre' => 'F. P. K., S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '25922556', 'per_nombre' => 'REMOTRAC, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '91814278', 'per_nombre' => 'CARGOTEC, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '34373519', 'per_nombre' => 'UNOPETROL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '29808766', 'per_nombre' => 'FAST MAIL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '43236669', 'per_nombre' => 'DISTEPORT, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5531209', 'per_nombre' => 'SUR COLOR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '69723125', 'per_nombre' => 'IMAGINOVA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '102977348', 'per_nombre' => 'SSI GROUP, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '82615195', 'per_nombre' => 'EXPRESO YA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '94421463', 'per_nombre' => 'AEROPETROL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '24408999', 'per_nombre' => 'NAVEGA.COM, S.A..', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '81644787', 'per_nombre' => 'HOSE DEPOT, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '69936463', 'per_nombre' => 'PAPA POLLO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '100738311', 'per_nombre' => 'ARGANZUELA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '28155106', 'per_nombre' => 'LA PANERIA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3454916', 'per_nombre' => 'CONTECNICA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5820065', 'per_nombre' => 'SAN MIGUEL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5893666', 'per_nombre' => 'EXPOGRANEL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '76141748', 'per_nombre' => 'LA PANOTECA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1221744', 'per_nombre' => 'ARCA DE NOE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '97597899', 'per_nombre' => 'ESTARBORETO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '42498244', 'per_nombre' => 'MOVI IMPORT, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '965634', 'per_nombre' => 'EL BUEN PAN, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26155389', 'per_nombre' => 'PUENTE NUEVO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '9808698', 'per_nombre' => 'POLLO CARIBE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26395789', 'per_nombre' => 'PUERTO LIBRE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '48525189', 'per_nombre' => 'VALLE DORADO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3881830', 'per_nombre' => 'ROBLE BLANCO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '42275261', 'per_nombre' => 'CASA VERANDA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5750814', 'per_nombre' => 'CARGO EXPRESO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '321052', 'per_nombre' => 'UNO GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '321737', 'per_nombre' => 'SEGUROS G & T, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '16904397', 'per_nombre' => 'AEC REPUESTOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7097921', 'per_nombre' => 'BUS-REPUESTOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '29425158', 'per_nombre' => 'LONAS SEGOVIA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '904945', 'per_nombre' => 'POLLO CAMPERO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7267525', 'per_nombre' => 'SONIDO SEGURO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '74650068', 'per_nombre' => 'BROADCOM GROUP, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '102732329', 'per_nombre' => 'SISTEMAS ASTER, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '16895770', 'per_nombre' => 'GRUPO COMUDISA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '78411610', 'per_nombre' => 'INVERSORES LYD, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '81766173', 'per_nombre' => 'FERRETERIA EPA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '78240050', 'per_nombre' => 'GRUPO DE TODOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '749303', 'per_nombre' => 'CENTRAL MOTRIZ, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '66283051', 'per_nombre' => 'TACTICAL GROUP, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '41565576', 'per_nombre' => 'GRUPO FARMAGUA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5581737', 'per_nombre' => 'EMPRESAS TANDY, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '65451848', 'per_nombre' => 'ELEVADORES UNO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '61323136', 'per_nombre' => 'INFO IDENTIDAD, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '64973719', 'per_nombre' => 'HOTEL LONGARONE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '14941368', 'per_nombre' => 'FINCA LA VIRGEN, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '76447472', 'per_nombre' => 'POLLO PICONCITO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '91531926', 'per_nombre' => 'GRUPO EL DORADO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '76324826', 'per_nombre' => 'CORPORACION PTR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '101035470', 'per_nombre' => 'CENTRO PAPELERO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '101065833', 'per_nombre' => 'ZEUGYS NETWORKS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '57628963', 'per_nombre' => 'SALINA PACIFICO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '108844633', 'per_nombre' => 'RH DIESEL PARTS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '735582', 'per_nombre' => 'FICOHSA SEGUROS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3718069', 'per_nombre' => 'INDUSTRIA CHINA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '42415292', 'per_nombre' => 'AXALTA GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '32375913', 'per_nombre' => 'NUEVOS ALMACENES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '169692', 'per_nombre' => 'ALMACEN EL VAPOR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '57417415', 'per_nombre' => 'AGUNSA GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '70032629', 'per_nombre' => 'BOERPERD DEL SUR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4275217', 'per_nombre' => 'SEGUROS PRIVANZA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7849583', 'per_nombre' => 'INVERSIONES R.M., S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '98003267', 'per_nombre' => 'AMAYA Y ABOGADOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '109786270', 'per_nombre' => 'INVERSIONES MALU, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5956331', 'per_nombre' => 'RESORTES DE LEON, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '63400871', 'per_nombre' => 'CORPORACION SFERA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '96874449', 'per_nombre' => 'AUTOLLANTAS GOMEZ, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '102769478', 'per_nombre' => 'EL LLANO SANTIAGO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '737909', 'per_nombre' => 'TECNICA UNIVERSAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '96169176', 'per_nombre' => 'RED PETROLEUM GAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '93696698', 'per_nombre' => 'EL PORTAL DEL SUR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '85718262', 'per_nombre' => 'COMERCIAL SMILIST, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '42672708', 'per_nombre' => 'SERVICIOS PREMIER, S.A..', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '110865294', 'per_nombre' => 'CONACASTE DEL SUR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '12777633', 'per_nombre' => 'FERRETERIA PETAPA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '596198K', 'per_nombre' => 'REPUESTOS ESTRADA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '6878733', 'per_nombre' => 'MANGUERAS DEL SUR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '108784002', 'per_nombre' => 'REPUESTOS EL RAYO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '108063445', 'per_nombre' => 'CORPORACION NAVAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '35355913', 'per_nombre' => 'ALTURISA GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4711122', 'per_nombre' => 'SISTEMAS DE PESAJE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '16895541', 'per_nombre' => 'CORPORACION BATRES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '6521150', 'per_nombre' => 'CORPORACION MERINO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '67175082', 'per_nombre' => 'LA BUONA AUBERGINA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5139511', 'per_nombre' => 'CHIQUITA GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '108791211', 'per_nombre' => 'CORPORACION MALBEC, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '75265508', 'per_nombre' => 'CENTRO DE LIMPIEZA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3181561', 'per_nombre' => 'PRESTEGARD ELECTRO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '54284252', 'per_nombre' => 'SERVICA INDUSTRIAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '63998106', 'per_nombre' => 'MARTEC DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '30449901', 'per_nombre' => 'RESTAURANTES SARITA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '36677167', 'per_nombre' => 'CONSTRUCTORA CODICO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '79246818', 'per_nombre' => 'INMOBILIARIA CAFRAN, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '107957795', 'per_nombre' => 'CONSTRUHERRAMIENTAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '9886052', 'per_nombre' => 'DEPOSITO DE PESCADO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '324396', 'per_nombre' => 'SEGUROS UNIVERSALES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4751124', 'per_nombre' => 'BODEGA FARMACEUTICA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '70664064', 'per_nombre' => 'ALIMENTOS DECORADOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '690470K', 'per_nombre' => 'MATERIALES GRAFICOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '68457804', 'per_nombre' => 'INTERLAKEN SERVICIOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7378106', 'per_nombre' => 'OPERADORA DE TIENDAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '70926883', 'per_nombre' => 'INVERSIONES MARPENSA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '73999504', 'per_nombre' => 'DOLLARCITY GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '8503443', 'per_nombre' => 'OPERADORA DE BODEGAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '45828806', 'per_nombre' => 'COBERTURA INDUSTRIAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '29552869', 'per_nombre' => 'AUTOKIA DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '98782630', 'per_nombre' => 'CARBOGRAFITOS EDISON, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '9809287', 'per_nombre' => 'CONSTRUCTORA MARHNOS, S.A. DE CAPITALVARIABLE', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '6844162', 'per_nombre' => 'LA CASA DEL TORNILLO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1532227', 'per_nombre' => 'FORMULARIOS STANDARD, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '61855170', 'per_nombre' => 'COMBUSTIBLES CHAPINES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '2839113', 'per_nombre' => 'TROPIGAS DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '51025507', 'per_nombre' => 'INDUSTRIAS TRES PICOS, S.A..', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1536230', 'per_nombre' => 'CLUTCHES DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '78485428', 'per_nombre' => 'APM TERMINALS QUETZAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '69674264', 'per_nombre' => 'MULTILLANTAS LOS TRES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '8175926', 'per_nombre' => 'INTCOMEX DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4963040', 'per_nombre' => 'DISTRIBUIDORA SATURNO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '38669161', 'per_nombre' => 'CORPORACION PORTUARIA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '107828987', 'per_nombre' => 'FERRETERÍA LA ARENERA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '79746357', 'per_nombre' => 'PACIFIC FINS GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '98607154', 'per_nombre' => 'ELECTROMA DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '51243814', 'per_nombre' => 'GASOLINERAS EXCLUSIVAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '6654274', 'per_nombre' => 'DIVISION DMC GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '66491355', 'per_nombre' => 'GASOLINERA SANTO TOMAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '86332147', 'per_nombre' => 'DISTRIBUIDORA EL CANAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '25193201', 'per_nombre' => 'CORPORACION EL ZAPOTAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '91890594', 'per_nombre' => 'ENERGIA Y COMBUSTIBLES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '14940450', 'per_nombre' => 'PRICESMART (GUATEMALA), S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '43305393', 'per_nombre' => 'FERCOMPAIZ SANTO TOMAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '106547003', 'per_nombre' => 'CORPORATIVO SAN MARTÍN, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '70032955', 'per_nombre' => 'KLADRUBER DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '82110476', 'per_nombre' => 'TRANSPORTES EL EXPRESO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '82774005', 'per_nombre' => 'AMERICAN BUS REPUESTOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '58092161', 'per_nombre' => 'DESARROLLOS LAS ARCADAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7571836', 'per_nombre' => 'SERVICIOS DE DOCUMENTOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '983675', 'per_nombre' => 'BEECHCRAFT DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5032601', 'per_nombre' => 'PASTELERÍA Y REPOSTERÍA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '99225778', 'per_nombre' => 'BOTIQUINES DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '332917', 'per_nombre' => 'COFIÑO STAHL Y COMPAÑIA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '64825612', 'per_nombre' => 'RADIADORES PORTOCARRERO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '108551938', 'per_nombre' => 'TECNOLOGÍA AUTOMATIZADA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '54290651', 'per_nombre' => 'GRUPO COMERCIAL MARITZA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '47294787', 'per_nombre' => 'PROGRAMACION EMPRESARIAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '82595089', 'per_nombre' => 'GASOLINERAS CONSOLIDADAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3882314', 'per_nombre' => 'RESTAURANTES Y SERVICIOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5498104', 'per_nombre' => 'COMUNICACIONES CELULARES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '45435499', 'per_nombre' => 'GMG COMERCIAL  GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5402026', 'per_nombre' => 'INTERNACIONAL DE CALZADO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '69313660', 'per_nombre' => 'COMFORTSTAR DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
        ]);
        DB::table('personas')->insert([
            ['per_nit' => '3853616', 'per_nombre' => 'COMPAÑIA COMERCIAL LIBRA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '80260497', 'per_nombre' => 'RESTAURANTES DON CARNITAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '65617215', 'per_nombre' => 'IMPORTADORA LA GRAN UNION, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '62161385', 'per_nombre' => 'RPC SERVICIOS COMERCIALES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '45322414', 'per_nombre' => 'CARBURANTES DEL ATLANTICO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4521587', 'per_nombre' => 'INDUSTRIA DE HAMBURGUESAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26519577', 'per_nombre' => 'POTENCIA DIESEL REPUESTOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '979767', 'per_nombre' => 'DISTRIBUIDORA ELECTRONICA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5616824', 'per_nombre' => 'LUBRICANTES E IMPORTACION, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '77110897', 'per_nombre' => 'DROGUERIA CENTRO HISTORICO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '74433032', 'per_nombre' => 'COMERCIALIZADORA CONACASTE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '2313058K', 'per_nombre' => 'MAYORISTAS DE ELECTRICIDAD, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '103319700', 'per_nombre' => 'GRUPO DE TIENDAS ASOCIADAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '2267375K', 'per_nombre' => 'A.E.C. REPUESTOS ZONA DOCE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '33265275', 'per_nombre' => 'DISTRIBUIDORA LA CONQUISTA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '46927891', 'per_nombre' => 'BUSINESS SOLUTIONS PARTNERS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '98844253', 'per_nombre' => 'RENDIMIENTO EN COMBUSTIBLES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1539167', 'per_nombre' => 'CELASA INGENIERIA Y EQUIPOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4731301', 'per_nombre' => 'DISTRIBUIDORA DEL ATLANTICO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4146972', 'per_nombre' => 'PRONE PROMOCIONES Y NEGOCIOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '44247842', 'per_nombre' => 'MUNDO DE BANDERAS INDUSTRIAL, S.A..', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5686865', 'per_nombre' => 'POLLO BRUJO DE CENTROAMERICA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '77302133', 'per_nombre' => 'MAGUEL RJR FORMULA COMERCIAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '74752537', 'per_nombre' => 'OROSHELL CENTRAL LUBRICANTES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5549353', 'per_nombre' => 'COCODRILO CABLES Y ACCESORIOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1592882', 'per_nombre' => 'DISTRIBUIDORA CENTROAMERICANA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '14946688', 'per_nombre' => 'OPERADORA DE SERVICIOS VIALES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '91342368', 'per_nombre' => 'FUENTE COMBUSTIBLES DEL NORTE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5247993', 'per_nombre' => 'CORPORACION RADIO ELECTRONICA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '66649595', 'per_nombre' => 'MACRO QUIMICA CENTROAMERICANA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '20330995', 'per_nombre' => 'TRANSPORTES TERRESTRES FRANCO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '21056234', 'per_nombre' => 'ALIMENTOS CORPORATIVOS CORALSA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '44901569', 'per_nombre' => 'LINEAS DE SOLUCIONES FLEXIBLES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '91010748', 'per_nombre' => 'INTERCONTINENTAL DEL ATLANTICO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '67225802', 'per_nombre' => 'IMPORTACIONES Y EQUIPOS IMEQMO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '326445', 'per_nombre' => 'EMPRESA ELECTRICA DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '59475471', 'per_nombre' => 'COMERCIO Y SERVICIOS DEL NORTE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '97487147', 'per_nombre' => 'GASOLINERA NORTH WEST AMATITLAN, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '599635K', 'per_nombre' => 'LINEAS TERRESTRES GUATEMALTECAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '9929290', 'per_nombre' => 'TELECOMUNICACIONES DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '83101462', 'per_nombre' => 'INVERSIONES Y PETROLEOS DEL SOL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '73639915', 'per_nombre' => 'EQUIPOS Y SUMINISTROS DE PESAJE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '30370299', 'per_nombre' => 'TRANSPORTE, EMPAQUE Y ALMACENAJE, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '106204572', 'per_nombre' => 'ESTACIONES Y SERVICIOS PETROGALO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '59463430', 'per_nombre' => 'OPERADORA DE CENTRO DE SERVICIOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '527303K', 'per_nombre' => 'TRANSPORTES AEREOS GUATEMALTECOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7257252', 'per_nombre' => 'COMERCIAL DE INVERSIONES SANTANA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '88921786', 'per_nombre' => 'SERVICIO TECNICO DE EXTINGUIDORES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '82640408', 'per_nombre' => 'INVERSIONES GLOBALES CORPORATIVAS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '103984925', 'per_nombre' => 'GASOLINERA NORTH WEST LLANO LARGO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '98054155', 'per_nombre' => 'INGENIERIA Y EQUIPOS INDUSTRIALES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '22278079', 'per_nombre' => 'GENERAL DE MATERIALES Y AGREGADOS, S.A..', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '54885051', 'per_nombre' => 'CONSTRUCTORES Y CONSULTORES VIALES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '55150683', 'per_nombre' => 'CONSTRUCCION MOVIMIENTO Y VIVIENDA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '98664581', 'per_nombre' => 'PRODUCTOS Y SERVICIOS AUTOMOTRICES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '99811413', 'per_nombre' => 'SERVICES CORPORATION INTERNATIONAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26726378', 'per_nombre' => 'NEGOCIOS CONSOLIDADOS DEL PACIFICO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26673347', 'per_nombre' => 'CORPORACION DE LLANTAS Y SERVICIOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '70021147', 'per_nombre' => 'DISTRIBUIDORA DEL CENTRO DE IZABAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3853691', 'per_nombre' => 'SOCIEDAD INTERNACIONAL DE SERVICIOS, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7328842', 'per_nombre' => 'LIBRERÍA Y PAPELERÍA PROGRESO CINCO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4490363', 'per_nombre' => 'COMPAÑIA UNIVERSAL DE REFRIGERACION, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5892015', 'per_nombre' => 'PROMOTORA INTERNACIONAL EL TRIANGULO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '82280363', 'per_nombre' => 'INNOVACIONES MEDICAS INTERNACIONALES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '79295274', 'per_nombre' => 'LATAM HOTEL CORPORATION DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '86743643', 'per_nombre' => 'CONSULTORIA Y ARQUITECTURA AMBIENTAL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '72715340', 'per_nombre' => 'PROVEEDORA DE DERIVADOS DEL PETROLEO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '39082660', 'per_nombre' => 'PROMOTORA DE DIVERSIONES DEL PACIFICO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4556984', 'per_nombre' => 'COMPAÑIA DE EQUIPO MEDICO-HOSPITALARIO, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '109898559', 'per_nombre' => 'IMPORTADORA DE LLANTAS Y SERVICIOS EGA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '6014453', 'per_nombre' => 'COMERCIAL DISTRIBUIDORA DE COMBUSTIBLES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '95126708', 'per_nombre' => 'ESTACIONES DE COMBUSTIBLES DE GUATEMALA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5816580', 'per_nombre' => 'SERVICIOS MERCANTILES DE CENTRO AMERICA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '81510780', 'per_nombre' => 'COMUNICACIONES METROPOLITANAS CABLECOLOR, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '575461', 'per_nombre' => 'PRODUCTIVE BUSINESS SOLUTIONS (GUATEMALA), S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '77486927', 'per_nombre' => 'INDUSTRIAS TECNOLOGICAS DE MOTORES DIESEL, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '68142463', 'per_nombre' => 'FRANQUICIA DE LIMPIEZA, SERVICIO Y CALIDAD, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '80177336', 'per_nombre' => 'IMPORTADORA, EXPORTADORA Y DISTRIBUIDORA RUBI, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '72727942', 'per_nombre' => 'ASESORIA Y DESARROLLO DE PROYECTOS INTERNACIONALES, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5049288', 'per_nombre' => 'EXPORTADORA E IMPORTADORA EN GENERAL Y SERVICIOS A LA INDUSTRIA SOLARSA, S.A.', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '652818K', 'per_nombre' => 'ISRAEL VARGAS JIMÉNEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1388042K', 'per_nombre' => 'EMILSA TREJO CRUZ DE MARTÍNEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1118277', 'per_nombre' => 'ARMANDO CHANG HOU', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '89143574', 'per_nombre' => 'BERTILA SOLIS MONTERROSO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '10139168', 'per_nombre' => 'ROBERTO GRAMAJO ALVARADO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3865258', 'per_nombre' => 'FRANCISCO GARCIA ALVAREZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '48958824', 'per_nombre' => 'ANA LUCÍA ALDANA LORENZO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '83674071', 'per_nombre' => 'JOSÉ LUIS URRUTIA DÍAZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '107827212', 'per_nombre' => 'SEBASTIAN ZAPON RABINAL', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '14158469', 'per_nombre' => 'OMAR JOSE RIVAS SOLORZANO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5776457', 'per_nombre' => 'HSIU FONG HUANG', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '2538423', 'per_nombre' => 'NERY ELMER VALDES ORELLANA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '36832553', 'per_nombre' => 'EBERT JOEL YUCA QUIROZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '9815015', 'per_nombre' => 'NERY RUBEN OLIVA SOSA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '38406454', 'per_nombre' => 'LUIS DAVID RIVERA HINTZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '64791629', 'per_nombre' => 'JORGE LUIS MORATAYA BENITEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '14197278', 'per_nombre' => 'CANDELARIO HERRERA LOPEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26754363', 'per_nombre' => 'ELVA MARINA GUEVARA POZUELOS DE CASTELLANOS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '28869710', 'per_nombre' => 'JUAN CARLOS CÁCERES DEL CID', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1329480', 'per_nombre' => 'JUAN JACOBO CASTAÑEDA ILLESCAS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '33458898', 'per_nombre' => 'LESBIA RUBY ESTRADA GAITÁN DE GUTIERREZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '9534806', 'per_nombre' => 'JULIO CESAR BUCH SIQUINAJAY', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '29481538', 'per_nombre' => 'NOHE JONATAN VÁSQUEZ OROZCO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '57121532', 'per_nombre' => 'JOSUE ELISEO AGUSTIN ESTEBAN', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26065177', 'per_nombre' => 'HUGO ARNOLDO GAMBOA CALDERON', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '41857755', 'per_nombre' => 'SAID ABRAHAM CUMES SAMAYOA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7348134', 'per_nombre' => 'MIRNA GLADIS CALDERON VALDÉS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5034159', 'per_nombre' => 'NERY NEFTALÍ SALGUERO PORTILLO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '85068101', 'per_nombre' => 'ANDY GUSTAVO CATALÁN VELA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '90507959', 'per_nombre' => 'JOSÉ ALFREDO SANTOS RAMÍREZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '93708912', 'per_nombre' => 'JIMMY JAVIER TOLEDO PATIÑO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '6735320', 'per_nombre' => 'LUIS ALFONSO MENOCAL LEZANA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '16379845', 'per_nombre' => 'ABIMAÉL ESAÚ SANTOS DE LEON', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5948940', 'per_nombre' => 'EDGAR ALFREDO SIGUENZA LOPEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '31214274', 'per_nombre' => 'MARIO ROBERTO GONZÁLEZ PAIZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '23222239', 'per_nombre' => 'OSCAR ENRIQUE TOBAR AGUSTIN', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '50953613', 'per_nombre' => 'JENY LISSETTE CARRILLO VANEGAS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '85450103', 'per_nombre' => 'SUSANA NOHEMI GARCÍA ESPEL', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '95053719', 'per_nombre' => 'SAIRA MABILIA ORELLANA DUARTE', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '8111723', 'per_nombre' => 'CARLOS RAFAEL CEBALLOS VILLEDA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '1534351', 'per_nombre' => 'AUGUSTO RUBÉN CHAVEZ QUINTANILLA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '38890976', 'per_nombre' => 'DANIEL HERNAN MORALES SOBERANIS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '31523854', 'per_nombre' => 'CARLOS ULISES GIRON DE LEON', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '98528815', 'per_nombre' => 'ANDREA NARAHY BAMACA FUENTES', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '102404275', 'per_nombre' => 'EDUARDO MATEO GONZÁLEZ BARRIOS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '14182602', 'per_nombre' => 'OSMAR ALCIDES JUÁREZ BARILLAS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '32983433', 'per_nombre' => 'IRMA LUCRECIA LACÁN GONZÁLEZ DE ROJAS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '57632332', 'per_nombre' => 'MARIO ORLANDO USHER MORALES', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '10332855', 'per_nombre' => 'SILVIA JANETH DUEÑAS JORDAN', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '24217832', 'per_nombre' => 'WIDMAN EJBERTO CONTRERAS SANTOS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '41360680', 'per_nombre' => 'MANOLA EUGENIA SARAVIA GALINDO DE MUÑOZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '43836127', 'per_nombre' => 'YANIRA ARACELI BARRERA LEMUS DE CANTORAL', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '465403K', 'per_nombre' => 'GUSTAVO ADOLFO FIGUEROA SANCHEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '56229275', 'per_nombre' => 'BRENDA DOROTEA VELÁSQUEZ GONZÁLEZ DE FELIX', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7646658', 'per_nombre' => 'EDWING ROBERTO HERRARTE RODAS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '90780396', 'per_nombre' => 'MARVIN JOHANES MAYORGA ARGUETA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '88589161', 'per_nombre' => 'MARTA PATRICIA RIVERA ORELLANA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '103689966', 'per_nombre' => 'ENRIQUE MARTÍN SAMAYOA SOTO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '76868354', 'per_nombre' => 'KELVIN ALBERTO GUZMÁN MARROQUÍN', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '96781912', 'per_nombre' => 'WENDY CAROLINA LEMUS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '43069789', 'per_nombre' => 'EVELIN XIOMARA YAT LOPEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7642210', 'per_nombre' => 'SERGIO ARMANDO CASTILLO MELGAR', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '37142070', 'per_nombre' => 'CLAUDIA LISBETH QUEVEDO MELENDRES DE CALDERON', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '80059430', 'per_nombre' => 'WILLIAMS DANIEL MOLINA RODRÍGUEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '36434353', 'per_nombre' => 'MAURICIO UBALDO ALFARO RAMIREZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '26363585', 'per_nombre' => 'CARLOS HUMBERTO DÍAZ RAMÍREZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '43912591', 'per_nombre' => 'MARIA MAGDALENA ZEPEDA RIVERA DE CASTRO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '10003967', 'per_nombre' => 'KARLA ELIZABETH HERRERA MORALES', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '45100519', 'per_nombre' => 'EDWIN ALEXANDER SOLIS GUERRA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '8474885', 'per_nombre' => 'CARLOS HUMBERTO RAMÍREZ MALDONADO', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '34208895', 'per_nombre' => 'SERGIO DE JESUS ARREDONDO GARCÍA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '8407355', 'per_nombre' => 'CLARENCIO ARIEL MONTEJO MARTÍNEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '7595646', 'per_nombre' => 'WILHELM ROHALDO GONZALEZ BARRIENTOS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '82131910', 'per_nombre' => 'ISRAEL DE JESUS MORALES MORAN', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '43101062', 'per_nombre' => 'HEIDY ELIZABETH RECINOS HERRERA DE MICHE', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '33906742', 'per_nombre' => 'ANGELICA BEATRIS HERNÁNDEZ ORTÍZ DE PEREDA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5839971', 'per_nombre' => 'BELMER FRANCISCO HERNANDEZ LIMA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '89212835', 'per_nombre' => 'MARLON ALEXANDER GUZMÁN DE LEON', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3844706', 'per_nombre' => 'LUDWING VENANCIO GUERRA PEREZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '2255790', 'per_nombre' => 'TORIBIO DE JESÚS MAZARIEGOS MÉNDEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '4547365', 'per_nombre' => 'SALVADOR ERNESTO CÁRCAMO SALINAS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '5318734', 'per_nombre' => 'GLADIS DEL CARMEN CONTRERAS POLANCO DE GUERRA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '100114539', 'per_nombre' => 'ANDREA DEL CARMEN CARDENAS VALDEZ', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '17462878', 'per_nombre' => 'BRAILOWSKY SMILES REYES RIVAS', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3377830', 'per_nombre' => 'EMPRESA PORTUARIA QUETZAL', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '107919419', 'per_nombre' => 'SERVICIOS DE SANITIZACION Y DESINFECCION A&E', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '52449092', 'per_nombre' => 'ASOCIACION PARA EL DESARROLLO ECONOMICO Y SOCIAL DE AEROPUERTOS Y PUERTOS COMBEX-IM', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '55905412', 'per_nombre' => 'OD GUATEMALA Y COMPAÑIA LIMITADA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '3133222', 'per_nombre' => 'EMPRESA PORTUARIA NACIONAL SANTO TOMAS DE CASTILLA', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '80067735', 'per_nombre' => 'COMISARIATO POPULAR COPROPIEDAD', 'per_direccion' => 'Ciudad', 'per_tipoContribuyente' => 2, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '24104817', 'per_nombre' => 'GUILLERMO ALEJANDRO SOLÓRZANO DEBROY', 'per_direccion' => '12 avenida 12-48, zona 2, Colonia Ciudad Nueva', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['per_nit' => '93504500', 'per_nombre' => 'JHOSELINE PAOLA PELICÓ ROCHE', 'per_direccion' => 'zona 5', 'per_tipoContribuyente' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
        ]);
    }
}
